# Generated by Django 3.0.5 on 2020-05-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200526_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/home/manhle/Pictures/1.png', upload_to='static/images'),
        ),
    ]
