# Generated by Django 3.0.5 on 2020-05-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200526_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='1.png', upload_to='static/images'),
        ),
    ]
